import pygame as pg
#This is a list of every frame for all actions the player can take
player = [
    #Walking dictionary
    {
    "walk back" : [
        pg.image.load("img/game_files/player_walk/player_back1.png"),
        pg.image.load("img/game_files/player_walk/player_back2.png"),
        pg.image.load("img/game_files/player_walk/player_back3.png"),
        pg.image.load("img/game_files/player_walk/player_back4.png"),
        pg.image.load("img/game_files/player_walk/player_back5.png"),
        pg.image.load("img/game_files/player_walk/player_back6.png"),
        pg.image.load("img/game_files/player_walk/player_back7.png"),
        pg.image.load("img/game_files/player_walk/player_back8.png"),
        ],
    "walk back-left" : [
        pg.image.load("img/game_files/player_walk/player_backleft1.png"),
        pg.image.load("img/game_files/player_walk/player_backleft2.png"),
        pg.image.load("img/game_files/player_walk/player_backleft3.png"),
        pg.image.load("img/game_files/player_walk/player_backleft4.png"),
        pg.image.load("img/game_files/player_walk/player_backleft5.png"),
        pg.image.load("img/game_files/player_walk/player_backleft6.png"),
        pg.image.load("img/game_files/player_walk/player_backleft7.png"),
        pg.image.load("img/game_files/player_walk/player_backleft8.png"),
        ],
    "walk back-right" : [
        pg.image.load("img/game_files/player_walk/player_backright1.png"),
        pg.image.load("img/game_files/player_walk/player_backright2.png"),
        pg.image.load("img/game_files/player_walk/player_backright3.png"),
        pg.image.load("img/game_files/player_walk/player_backright4.png"),
        pg.image.load("img/game_files/player_walk/player_backright5.png"),
        pg.image.load("img/game_files/player_walk/player_backright6.png"),
        pg.image.load("img/game_files/player_walk/player_backright7.png"),
        pg.image.load("img/game_files/player_walk/player_backright8.png"),
        ],
    "walk front" : [
        pg.image.load("img/game_files/player_walk/player_front1.png"),
        pg.image.load("img/game_files/player_walk/player_front2.png"),
        pg.image.load("img/game_files/player_walk/player_front3.png"),
        pg.image.load("img/game_files/player_walk/player_front4.png"),
        pg.image.load("img/game_files/player_walk/player_front5.png"),
        pg.image.load("img/game_files/player_walk/player_front6.png"),
        pg.image.load("img/game_files/player_walk/player_front7.png"),
        pg.image.load("img/game_files/player_walk/player_front8.png"),
        ],
    "walk front-left" : [
        pg.image.load("img/game_files/player_walk/player_frontleft1.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft2.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft3.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft4.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft5.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft6.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft7.png"),
        pg.image.load("img/game_files/player_walk/player_frontleft8.png"),
        ],
    "walk front-right": [
        pg.image.load("img/game_files/player_walk/player_frontright1.png"),
        pg.image.load("img/game_files/player_walk/player_frontright2.png"),
        pg.image.load("img/game_files/player_walk/player_frontright3.png"),
        pg.image.load("img/game_files/player_walk/player_frontright4.png"),
        pg.image.load("img/game_files/player_walk/player_frontright5.png"),
        pg.image.load("img/game_files/player_walk/player_frontright6.png"),
        pg.image.load("img/game_files/player_walk/player_frontright7.png"),
        pg.image.load("img/game_files/player_walk/player_frontright8.png"),
    ],
    "walk left": [
        pg.image.load("img/game_files/player_walk/player_left1.png"),
        pg.image.load("img/game_files/player_walk/player_left2.png"),
        pg.image.load("img/game_files/player_walk/player_left3.png"),
        pg.image.load("img/game_files/player_walk/player_left4.png"),
        pg.image.load("img/game_files/player_walk/player_left5.png"),
        pg.image.load("img/game_files/player_walk/player_left6.png"),
        pg.image.load("img/game_files/player_walk/player_left7.png"),
        pg.image.load("img/game_files/player_walk/player_left8.png"),
    ],
    "walk right": [
        pg.image.load("img/game_files/player_walk/player_right1.png"),
        pg.image.load("img/game_files/player_walk/player_right2.png"),
        pg.image.load("img/game_files/player_walk/player_right3.png"),
        pg.image.load("img/game_files/player_walk/player_right4.png"),
        pg.image.load("img/game_files/player_walk/player_right5.png"),
        pg.image.load("img/game_files/player_walk/player_right6.png"),
        pg.image.load("img/game_files/player_walk/player_right7.png"),
        pg.image.load("img/game_files/player_walk/player_right8.png"),
    ]}
    #Moving and shooting dictionary
    ,{
    "run shoot down": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_down8.png"),
    ],
    "run shoot down-left": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downleft8.png")
    ],
    "run shoot down-right": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_downright8.png"),
    ],
    "run shoot left": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_left8.png"),
    ],
    "run shoot right": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_right8.png"),
    ],
    "run shoot up": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_up8.png"),
    ],
    "run shoot up-left": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upleft8.png"),
    ],
    "run shoot up-right": [
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright1.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright2.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright3.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright4.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright5.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright6.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright7.png"),
        pg.image.load("img/game_files/player_run_shoot/run_shoot_upright8.png"),
    ]}
    #Stationary shooting dictionary
    ,{
    "shoot down": [
        pg.image.load("img/game_files/player_shoot/shoot_down1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_down8.png"),
    ],
    "shoot down-left": [
        pg.image.load("img/game_files/player_shoot/shoot_downleft1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downleft8.png")
    ],
    "shoot down-right": [
        pg.image.load("img/game_files/player_shoot/shoot_downright1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_downright8.png"),
    ],
    "shoot left": [
        pg.image.load("img/game_files/player_shoot/shoot_left1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_left8.png"),
    ],
    "shoot right": [
        pg.image.load("img/game_files/player_shoot/shoot_right1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_right8.png"),
    ],
    "shoot up": [
        pg.image.load("img/game_files/player_shoot/shoot_up1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_up8.png"),
    ],
    "shoot up-left": [
        pg.image.load("img/game_files/player_shoot/shoot_upleft1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upleft8.png"),
    ],
    "shoot up-right": [
        pg.image.load("img/game_files/player_shoot/shoot_upright1.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright2.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright3.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright4.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright5.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright6.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright7.png"),
        pg.image.load("img/game_files/player_shoot/shoot_upright_8.png"),
    ]}
    #Reloading dictionary
    ,{
    "reload back": [
        pg.image.load("img/game_files/player_reload/reload_back1.png"),
        pg.image.load("img/game_files/player_reload/reload_back2.png"),
        pg.image.load("img/game_files/player_reload/reload_back3.png"),
        pg.image.load("img/game_files/player_reload/reload_back4.png"),
        pg.image.load("img/game_files/player_reload/reload_back5.png"),
        pg.image.load("img/game_files/player_reload/reload_back6.png"),
        pg.image.load("img/game_files/player_reload/reload_back7.png"),
        pg.image.load("img/game_files/player_reload/reload_back8.png"),
    ],
    "reload back-left": [
        pg.image.load("img/game_files/player_reload/reload_backleft1.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft2.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft3.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft4.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft5.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft6.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft7.png"),
        pg.image.load("img/game_files/player_reload/reload_backleft8.png"),
    ],
    "reload back-right": [
        pg.image.load("img/game_files/player_reload/reload_backright1.png"),
        pg.image.load("img/game_files/player_reload/reload_backright2.png"),
        pg.image.load("img/game_files/player_reload/reload_bakright3.png"),
        pg.image.load("img/game_files/player_reload/reload_backright4.png"),
        pg.image.load("img/game_files/player_reload/reload_backright5.png"),
        pg.image.load("img/game_files/player_reload/reload_backright6.png"),
        pg.image.load("img/game_files/player_reload/reload_backright7.png"),
        pg.image.load("img/game_files/player_reload/reload_backright8.png"),
    ],
    "reload front": [
        pg.image.load("img/game_files/player_reload/reload_front1.png"),
        pg.image.load("img/game_files/player_reload/reload_front2.png"),
        pg.image.load("img/game_files/player_reload/reload_front3.png"),
        pg.image.load("img/game_files/player_reload/reload_front4.png"),
        pg.image.load("img/game_files/player_reload/reload_front5.png"),
        pg.image.load("img/game_files/player_reload/reload_front6.png"),
        pg.image.load("img/game_files/player_reload/reload_front7.png"),
        pg.image.load("img/game_files/player_reload/reload_front8.png"),
    ],
    "reload left": [
        pg.image.load("img/game_files/player_reload/reload_left1.png"),
        pg.image.load("img/game_files/player_reload/reload_left2.png"),
        pg.image.load("img/game_files/player_reload/reload_left3.png"),
        pg.image.load("img/game_files/player_reload/reload_left4.png"),
        pg.image.load("img/game_files/player_reload/reload_left5.png"),
        pg.image.load("img/game_files/player_reload/reload_left6.png"),
        pg.image.load("img/game_files/player_reload/reload_left7.png"),
        pg.image.load("img/game_files/player_reload/reload_left8.png"),
    ],
    "reload right": [
        pg.image.load("img/game_files/player_reload/reload_right1.png"),
        pg.image.load("img/game_files/player_reload/reload_right2.png"),
        pg.image.load("img/game_files/player_reload/reload_right3.png"),
        pg.image.load("img/game_files/player_reload/reload_right4.png"),
        pg.image.load("img/game_files/player_reload/reload_right5.png"),
        pg.image.load("img/game_files/player_reload/reload_right6.png"),
        pg.image.load("img/game_files/player_reload/reload_right7.png"),
        pg.image.load("img/game_files/player_reload/reload_right8.png"),
    ]}
    #Death dictionary
    ,{
    "death back": [
        pg.image.load("img/game_files/player_death/death_back1.png"),
        pg.image.load("img/game_files/player_death/death_back2.png"),
        pg.image.load("img/game_files/player_death/death_back3.png"),
        pg.image.load("img/game_files/player_death/death_back4.png"),
        pg.image.load("img/game_files/player_death/death_back5.png"),
        pg.image.load("img/game_files/player_death/death_back6.png"),
        pg.image.load("img/game_files/player_death/death_back7.png"),
        pg.image.load("img/game_files/player_death/death_back8.png"),
    ],
    "death back-left": [
        pg.image.load("img/game_files/player_death/death_backleft1.png"),
        pg.image.load("img/game_files/player_death/death_backleft2.png"),
        pg.image.load("img/game_files/player_death/death_backleft3.png"),
        pg.image.load("img/game_files/player_death/death_backleft4.png"),
        pg.image.load("img/game_files/player_death/death_backleft5.png"),
        pg.image.load("img/game_files/player_death/death_backleft6.png"),
        pg.image.load("img/game_files/player_death/death_backleft7.png"),
        pg.image.load("img/game_files/player_death/death_backleft8.png"),
    ],
    "death back-right": [
        pg.image.load("img/game_files/player_death/death_backright1.png"),
        pg.image.load("img/game_files/player_death/death_backright2.png"),
        pg.image.load("img/game_files/player_death/death_backright3.png"),
        pg.image.load("img/game_files/player_death/death_backright4.png"),
        pg.image.load("img/game_files/player_death/death_backright5.png"),
        pg.image.load("img/game_files/player_death/death_backright6.png"),
        pg.image.load("img/game_files/player_death/death_backright7.png"),
        pg.image.load("img/game_files/player_death/death_backright8.png"),
    ],
    "death front": [
        pg.image.load("img/game_files/player_death/death_front1.png"),
        pg.image.load("img/game_files/player_death/death_front2.png"),
        pg.image.load("img/game_files/player_death/death_front3.png"),
        pg.image.load("img/game_files/player_death/death_front4.png"),
        pg.image.load("img/game_files/player_death/death_front5.png"),
        pg.image.load("img/game_files/player_death/death_front6.png"),
        pg.image.load("img/game_files/player_death/death_front7.png"),
        pg.image.load("img/game_files/player_death/death_front8.png"),
    ],
    "death left": [
        pg.image.load("img/game_files/player_death/death_left1.png"),
        pg.image.load("img/game_files/player_death/death_left2.png"),
        pg.image.load("img/game_files/player_death/death_left3.png"),
        pg.image.load("img/game_files/player_death/death_left4.png"),
        pg.image.load("img/game_files/player_death/death_left5.png"),
        pg.image.load("img/game_files/player_death/death_left6.png"),
        pg.image.load("img/game_files/player_death/death_left7.png"),
        pg.image.load("img/game_files/player_death/death_left8.png"),
    ],
    "death right": [
        pg.image.load("img/game_files/player_death/death_right1.png"),
        pg.image.load("img/game_files/player_death/death_right2.png"),
        pg.image.load("img/game_files/player_death/death_right3.png"),
        pg.image.load("img/game_files/player_death/death_right4.png"),
        pg.image.load("img/game_files/player_death/death_right5.png"),
        pg.image.load("img/game_files/player_death/death_right6.png"),
        pg.image.load("img/game_files/player_death/death_right7.png"),
        pg.image.load("img/game_files/player_death/death_right8.png"),
    ]}
]


#This is a list of every frame for all actions a zombie can take
zombie = [
    #Walking dictionary
    {
    "walk front" : [
        pg.image.load("img/game_files/zombie_walk/zomb_front1.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front2.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front3.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front4.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front5.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front6.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front7.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front8.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front9.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_front10.png")
    ],
    "walk back" : [
        pg.image.load("img/game_files/zombie_walk/zomb_back1.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back2.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back3.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back4.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back5.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back6.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back7.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back8.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back9.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_back10.png")
    ],
    "walk right" : [
        pg.image.load("img/game_files/zombie_walk/zomb_right1.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right2.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right3.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right4.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right5.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right6.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right7.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right8.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right9.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_right10.png")
    ],
    "walk left" : [
        pg.image.load("img/game_files/zombie_walk/zomb_left1.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left2.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left3.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left4.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left5.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left6.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left7.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left8.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left9.png"),
        pg.image.load("img/game_files/zombie_walk/zomb_left10.png")
    ]}
    #Attacking dictionary
    ,{
    "attack front" : [
        pg.image.load("img/game_files/zombie_attack/attack_front1.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front2.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front3.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front4.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front5.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front6.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front7.png"),
        pg.image.load("img/game_files/zombie_attack/attack_front8.png"),
    ],
    "attack back" : [
        pg.image.load("img/game_files/zombie_attack/attack_back1.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back2.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back3.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back4.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back5.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back6.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back7.png"),
        pg.image.load("img/game_files/zombie_attack/attack_back8.png"),
    ],
    "attack right" : [
        pg.image.load("img/game_files/zombie_attack/attack_right1.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right2.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right3.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right4.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right5.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right6.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right7.png"),
        pg.image.load("img/game_files/zombie_attack/attack_right8.png"),
    ],
    "attack left" : [
        pg.image.load("img/game_files/zombie_attack/attack_left1.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left2.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left3.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left4.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left5.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left6.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left7.png"),
        pg.image.load("img/game_files/zombie_attack/attack_left8.png"),
    ]}
    #Death Dictionary
    ,{
    "death front" : [
        pg.image.load("img/game_files/zombie_death/death_front1.png"),
        pg.image.load("img/game_files/zombie_death/death_front2.png"),
        pg.image.load("img/game_files/zombie_death/death_front3.png"),
        pg.image.load("img/game_files/zombie_death/death_front4.png"),
        pg.image.load("img/game_files/zombie_death/death_front5.png"),
        pg.image.load("img/game_files/zombie_death/death_front6.png"),
        pg.image.load("img/game_files/zombie_death/death_front7.png"),
    ],
    "death back" : [
        pg.image.load("img/game_files/zombie_death/death_back1.png"),
        pg.image.load("img/game_files/zombie_death/death_back2.png"),
        pg.image.load("img/game_files/zombie_death/death_back3.png"),
        pg.image.load("img/game_files/zombie_death/death_back4.png"),
        pg.image.load("img/game_files/zombie_death/death_back5.png"),
        pg.image.load("img/game_files/zombie_death/death_back6.png"),
        pg.image.load("img/game_files/zombie_death/death_back7.png"),
    ],
    "death right" : [
        pg.image.load("img/game_files/zombie_death/death_right1.png"),
        pg.image.load("img/game_files/zombie_death/death_right2.png"),
        pg.image.load("img/game_files/zombie_death/death_right3.png"),
        pg.image.load("img/game_files/zombie_death/death_right4.png"),
        pg.image.load("img/game_files/zombie_death/death_right5.png"),
        pg.image.load("img/game_files/zombie_death/death_right6.png"),
        pg.image.load("img/game_files/zombie_death/death_right7.png"),
    ],
    "death left" : [
        pg.image.load("img/game_files/zombie_death/death_left1.png"),
        pg.image.load("img/game_files/zombie_death/death_left2.png"),
        pg.image.load("img/game_files/zombie_death/death_left3.png"),
        pg.image.load("img/game_files/zombie_death/death_left4.png"),
        pg.image.load("img/game_files/zombie_death/death_left5.png"),
        pg.image.load("img/game_files/zombie_death/death_left6.png"),
        pg.image.load("img/game_files/zombie_death/death_left7.png"),
    ]}
]
